name: Build and test

on: push

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'adopt'
            - name: Run tests
              run: make test MVN_FLAGS=-B -e
            -   name: Build
                run: make package MVN_FLAGS=-B -e
            - name: Publish Test Report
              if: success() || failure()
              uses: scacap/action-surefire-report@v1
